"""Python script export for pipeline reproducibility.

Provides :func:`generate_pipeline_script` to generate a standalone Python
script that reproduces the user's evaluation pipeline.
"""

from __future__ import annotations

from typing import Any


def generate_pipeline_script(config: dict[str, Any]) -> str:
    """Generate a reproducible Python script from a pipeline configuration.

    Parameters
    ----------
    config : dict
        Pipeline configuration containing column mapping, met/clo values,
        weight preset, threshold, and evaluation settings.

    Returns
    -------
    str
        Python script source code as a string.

    Examples
    --------
    >>> script = generate_pipeline_script({
    ...     "csv_path": "sensor_data.csv",
    ...     "column_map": {"air_temp_c": "temp", "radiant_temp_c": "mrt"},
    ...     "met": 1.2,
    ...     "clo": 0.5,
    ...     "threshold": 80.0,
    ... })
    >>> "import pandas as pd" in script
    True
    >>> "calculate_compliance" in script
    True
    """
    csv_path = config.get("csv_path", "your_sensor_data.csv")
    column_map = config.get("column_map", {})
    met = config.get("met", 1.2)
    clo = config.get("clo", 0.5)
    standard = config.get("standard", "7730-2005")
    category = config.get("category", "B")
    task_type = config.get("task_type", "general")
    nc_level = config.get("nc_level", "NC-35")
    co2_threshold = config.get("co2_threshold", "good")
    pollutant_threshold = config.get("pollutant_threshold", "good")
    threshold = config.get("threshold", 80.0)
    weight_preset = config.get("weight_preset")
    tsv_time_aware = config.get("tsv_time_aware", False)
    adaptive_standard = config.get("adaptive_standard", "ashrae")
    adaptive_acceptability = config.get("adaptive_acceptability", 80)
    adaptive_category = config.get("adaptive_category", "ii")

    # Build column map dict repr
    if column_map:
        col_map_repr = "{\n"
        for canonical, actual in column_map.items():
            col_map_repr += f'    "{canonical}": "{actual}",\n'
        col_map_repr += "}"
    else:
        col_map_repr = "{}  # auto-detect"

    lines = [
        '"""Auto-generated by comfio.gui() — IEQ evaluation pipeline.',
        "",
        "This script reproduces the evaluation pipeline configured in the GUI.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import pandas as pd",
        "from comfio import (",
        "    SensorData,",
        "    evaluate_thermal,",
        "    evaluate_visual,",
        "    evaluate_acoustic,",
        "    evaluate_iaq,",
        "    evaluate_spmv,",
        "    evaluate_adaptive_ashrae,",
        "    evaluate_adaptive_en,",
        "    evaluate_iaq_pollutants,",
        "    augment_tsv_cdf,",
        "    evaluate_tsv,",
        "    calculate_global_ieq,",
        "    calculate_compliance,",
        "    ieq_to_markdown,",
        "    ieq_to_csv,",
        ")",
        "",
        "",
        "# --- Configuration ---",
        f'CSV_PATH = "{csv_path}"',
        f"COLUMN_MAP = {col_map_repr}",
        f"MET = {met}",
        f"CLO = {clo}",
        f'STANDARD = "{standard}"',
        f'CATEGORY = "{category}"',
        f'TASK_TYPE = "{task_type}"',
        f'NC_LEVEL = "{nc_level}"',
        f'CO2_THRESHOLD = "{co2_threshold}"',
        f'POLLUTANT_THRESHOLD = "{pollutant_threshold}"',
        f"THRESHOLD = {threshold}",
        f"TSV_TIME_AWARE = {tsv_time_aware}",
        f'ADAPTIVE_STANDARD = "{adaptive_standard}"',
        f"ADAPTIVE_ACCEPTABILITY = {adaptive_acceptability}",
        f'ADAPTIVE_CATEGORY = "{adaptive_category}"',
    ]

    if weight_preset:
        lines.append(f'WEIGHT_PRESET = "{weight_preset}"')
    else:
        lines.append("WEIGHT_PRESET = None  # use default weights")

    lines.extend(
        [
            "",
            "",
            "def main() -> None:",
            '    """Run the IEQ evaluation pipeline."""',
            "    # Load data",
            "    df = pd.read_csv(CSV_PATH)",
            "    sensor = SensorData(df=df, column_map=COLUMN_MAP if COLUMN_MAP else None)",
            "    sensor.validate()",
            "",
            "    # Detect available domains",
            "    available = sensor.available_domains()",
            '    print(f"Available domains: {available}")',
            "",
            "    # Evaluate each domain",
            "    thermal_res = None",
            "    visual_res = None",
            "    acoustic_res = None",
            "    iaq_res = None",
            "    spmv_res = None",
            "    adaptive_res = None",
            "    pollutant_res = None",
            "    tsv_res = None",
            "",
            '    if "thermal" in available:',
            "        thermal_res = evaluate_thermal(",
            '            tdb=sensor.get_validated("air_temp_c"),',
            '            tr=sensor.get_validated("radiant_temp_c"),',
            '            vr=sensor.get_validated("air_velocity_ms"),',
            '            rh=sensor.get_validated("relative_humidity_pct"),',
            "            met=MET, clo=CLO, standard=STANDARD, category=CATEGORY,",
            "        )",
            "",
            "    # sPMV (needs only air_temp + rh)",
            '    if ("air_temp_c" in sensor.column_map and',
            '        "relative_humidity_pct" in sensor.column_map):',
            "        spmv_res = evaluate_spmv(",
            '            indoor_temp=sensor.get_validated("air_temp_c"),',
            '            indoor_rh=sensor.get_validated("relative_humidity_pct"),',
            "        )",
            "",
            '    if "visual" in available:',
            "        visual_res = evaluate_visual(",
            '            illuminance=sensor.get_validated("illuminance_lux"),',
            "            task_type=TASK_TYPE,",
            "        )",
            "",
            '    if "acoustic" in available:',
            "        acoustic_res = evaluate_acoustic(",
            '            laeq=sensor.get_validated("noise_laeq_db"),',
            "            nc_level=NC_LEVEL,",
            "        )",
            "",
            '    if "iaq" in available:',
            "        iaq_res = evaluate_iaq(",
            '            co2=sensor.get_validated("co2_ppm"),',
            "            threshold_level=CO2_THRESHOLD,",
            "        )",
            "",
            "    # Global IEQ",
            "    ieq_result = calculate_global_ieq(",
            "        thermal=thermal_res,",
            "        visual=visual_res,",
            "        acoustic=acoustic_res,",
            "        iaq=iaq_res,",
            "        pollutant_iaq=pollutant_res,",
            "        tsv=tsv_res,",
            "    )",
            "",
            "    # Compliance",
            "    report = calculate_compliance(ieq_result, threshold=THRESHOLD)",
            "",
            "    # Output",
            "    print(ieq_to_markdown(ieq_result, compliance_report=report))",
            "    print()",
            '    print("CSV scores:")',
            "    print(ieq_to_csv(ieq_result, compliance_report=report))",
            "",
            "",
            'if __name__ == "__main__":',
            "    main()",
        ]
    )

    return "\n".join(lines) + "\n"
